# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 100
  reviewers:
  - mandy-chessell
  - lpalashevski
  # Grouping of dependencies - useful to retain consistency & prevent build breaks
  groups:
    spring:
      patterns:
        - "*spring*"
        - "*tomcat*"
    janusgraph:
      patterns:
        - "*janusgraph*"
        - "*tinkerpop*"
        - "*elasticsearch*"
        - "*lucene*"
    slf4j:
      patterns:
        - "*slf4j*"
    jackson:
      patterns:
        - "com.fasterxml.*"
  ignore:
    - dependency-name: "org.apache.tinkerpop:tinkergraph-gremlin"
      versions: [ "1.0.0-20231003-025335.faa9072" ]
    - dependency-name: "org.janusgraph:janusgraph-core"
      versions: [ "1.0.0-20231003-025335.faa9072" ]
    - dependency-name: "org.janusgraph:janusgraph-inmemory"
      versions: [ "1.0.0-20231003-025335.faa9072" ]
    - dependency-name: "org.apache.tinkerpop:gremlin-driver"
      versions: [ "3.7.0" ]
    - dependency-name: "org.apache.tinkerpop:gremlin-driver"
      versions: [ "3.7.0" ]
    - dependency-name: "org.apache.tinkerpop:gremlin-core"
      versions: [ "3.7.0" ]
    - dependency-name: "org.apache.tinkerpop:gremlin-groovy"
      versions: [ "3.7.0" ]
    - dependency-name: "org.apache.tinkerpop:gremlin-shaded"
      versions: [ "3.7.0" ]
    - dependency-name: "org.elasticsearch.client:elasticsearch-rest-client"
      versions: [ "8.10.2" ]
    - dependency-name: "org.elasticsearch:elasticsearch"
      versions: [ "8.10.2" ]
    - dependency-name: "co.elastic.clients:elasticsearch-java"
      versions: [ "8.10.2" ]
- package-ecosystem: docker
  directory: "/open-metadata-resources/open-metadata-deployment/docker/platform"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 5
  reviewers:
  - mandy-chessell
  - lpalashevski
- package-ecosystem: docker
  directory: "/open-metadata-resources/open-metadata-deployment/docker/configure"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 5
  reviewers:
  - mandy-chessell
  - lpalashevski
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 10
  reviewers:
  - mandy-chessell
  - lpalashevski
