# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 100
  reviewers:
  - planetf1
  # Grouping of dependencies - useful to retain consistency & prevent build breaks
  groups:
    spring:
      patterns:
        - "*spring*"
    janusgraph:
      patterns:
        - "*janus*"
        - "*gremlin*"
        - "*elasticsearch*"
        - "*lucene*"
    slf4j:
      patterns:
        - "*slf4j*"
    jackson:
      patterns:
        - "com.fasterxml.*"
- package-ecosystem: docker
  directory: "/open-metadata-resources/open-metadata-deployment/docker/egeria"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 5
  reviewers:
  - planetf1
- package-ecosystem: docker
  directory: "/open-metadata-resources/open-metadata-deployment/docker/configure"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 5
  reviewers:
  - planetf1
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: monthly
    time: "03:00"
    timezone: "Etc/UTC"
  open-pull-requests-limit: 10
  reviewers:
  - planetf1
